### ISSUE TITLE
Add a PR template

### ISSUE THREAD

**Issue by ashketchupppp** [ashketchupppp/veff#10]
When you make a PR we want to make sure the raiser of the PR have checked certain things before they raise it. This may include things like
 - Have you updated the README if needed?

Add a PR template with a checklist of things for the raiser of the PR to check before they raise it
See here https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by Dhravya** [comment]
Hi there, I can do this one. would you like to assign it to me?

**Comment by Dhravya** [comment]
I've done the PR template check it out

**Comment by ashketchupppp** [comment]
Where?

**Comment by Dhravya** [comment]
in the templates branch

**Comment by ashketchupppp** [comment]
Looks good, make a PR and I will merge
